config/routes.rb
RedmineApp::Application.routes.draw do

  resources :projects do
    resources :responses, :only => [:index, :new, :create]
  end

  resources :responses do
    collection do
      post :add
      post :apply
      post :update_note
    end
  end

end

app/models/response.rb
# frozen_string_literal: true

class Response < ApplicationRecord
  include Redmine::SafeAttributes

  serialize :initial_status_ids
  serialize :tracker_ids
  serialize :organization_ids

  belongs_to :final_status, class_name: 'IssueStatus'
  belongs_to :author, :class_name => 'User'
  belongs_to :assigned_to, :class_name => 'Principal'
  belongs_to :project
  # rubocop:disable Rails/HasAndBelongsToMany
  has_and_belongs_to_many :roles, :join_table => "responses_roles", :dependent => :delete_all
  # rubocop:enable Rails/HasAndBelongsToMany

  safe_attributes "name", "initial_status_ids", "final_status_id",
                  "time_limit", "note",
                  "author_id", "project_ids",
                  "enabled", "organization_ids",
                  "tracker_ids", "assigned_to_id",
                  "project_id", "visibility"

  validates_presence_of :name
  validates_presence_of :author, :if => proc { |response| response.new_record? || response.author_id_changed? }

  scope :active, -> { where(enabled: true) }
  # scope :not_private, -> { where(is_private: false) }
  scope :sorted, -> { order(:name) }
  # scope :visible_by, ->(user) { where("is_private = ? OR author_id = ?", false, user.id) }
  before_save :remove_empty_value_from_serialized_field

  VISIBILITY_PRIVATE = 0
  VISIBILITY_ROLES = 1
  VISIBILITY_PUBLIC = 2

  validates :visibility, :inclusion => { :in => [VISIBILITY_PUBLIC, VISIBILITY_ROLES, VISIBILITY_PRIVATE] }

  # User's own responses without project (private or public)
  scope :owned_without_project, ->(user) do
    where(author_id: user.id, project_id: nil)
  end

  # Public responses from other users without project
  scope :public_from_others_without_project, ->(user) do
    where(visibility: VISIBILITY_PUBLIC, project_id: nil).where.not(author_id: user.id)
  end

  def self.global_for_project(user = User.current, project_id)
    scope = joins("INNER JOIN #{Project.table_name} ON #{table_name}.project_id = #{Project.table_name}.id").
      where("#{table_name}.project_id = ?", project_id)
    if user.admin?
      scope
    elsif user.memberships.any?
      scope.where(
        "author_id = ? AND #{table_name}.visibility = ?" +
          " OR #{table_name}.visibility = ?" +
          " OR (#{table_name}.visibility = ? AND #{table_name}.id IN (" +
          "SELECT DISTINCT res.id FROM #{table_name} res" +
          " INNER JOIN responses_roles res_ro on res_ro.response_id = res.id" +
          " INNER JOIN #{MemberRole.table_name} mr ON mr.role_id = res_ro.role_id" +
          " INNER JOIN #{Member.table_name} m ON m.id = mr.member_id AND m.user_id = ?" +
          " INNER JOIN #{Project.table_name} p ON p.id = m.project_id AND m.project_id = ?))",
        user.id, VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_ROLES, user.id, project_id)
    else
      none
    end
  end

  def allowed_target_projects
    Project.active
  end

  def self.available_for(user: User.current, status: nil, tracker: nil, project_id: nil)
    # User's own responses without project (always visible to the user)
    own_responses = Response.active.owned_without_project(user)

    # Responses linked to the project (visibility rules apply)
    project_responses = Response.active.global_for_project(user, project_id)

    # Public responses from others without project (only if user has permission)
    public_responses_from_others = []
    if user.allowed_to?(:use_public_responses, Project.find(project_id))
      public_responses_from_others = Response.active.public_from_others_without_project(user)
    end

    responses = own_responses.to_a + project_responses.to_a + public_responses_from_others.to_a
    responses = responses.select { |r| r.initial_status_ids.empty? || r.initial_status_ids.include?(status.id.to_s) } if status.present?
    responses = responses.select { |r| r.tracker_ids.empty? || r.tracker_ids.include?(tracker.id.to_s) } if tracker.present?
    responses.uniq
  end

  def remove_empty_value_from_serialized_field
    organization_ids.delete("") if organization_ids.present? && (organization_ids.include? "")
    initial_status_ids.delete("") if initial_status_ids.present? && (initial_status_ids.include? "")
    tracker_ids.delete("") if tracker_ids.present? && (tracker_ids.include? "")
  end
end

app/controllers/responses_controller.rb
# frozen_string_literal: true

class ResponsesController < ApplicationController
  before_action :find_optional_project, :only => [:index, :new, :create]
  before_action :find_response, :only => [:show, :edit, :update, :destroy]
  before_action :require_admin_or_author, :only => [:edit, :update]
  before_action :require_delete_permission, :only => [:destroy]
  before_action :require_global, :only => [:show]

  def index
    @responses = Response.sorted
    if @project
      @responses = @responses.global_for_project(User.current, @project.id)
    else
      @responses = @responses.owned_without_project(User.current)
    end
    respond_to do |format|
      format.html { render :layout => User.current.admin? ? 'admin' : 'base' }
    end
  end

  def show
    @initial_statuses = IssueStatus.where(id: @response.initial_status_ids)
    @final_status = IssueStatus.find_by_id(@response.final_status_id)
  end

  def new
    @response = Response.new
    @response.project = params[:project_id] ? Project.find(params[:project_id]) : nil
  end

  def create
    @response = Response.new
    @response.author = User.current
    @response.project = params[:response][:project_id].present? ? Project.find(params[:response][:project_id]) : nil
    @response.safe_attributes = params[:response]
    complete_response_attributes

    if @response.save
      respond_to do |format|
        format.html do
          flash[:notice] = l(:notice_response_successfully_created)
          redirect_to responses_path if @response.project.blank?
          redirect_to project_responses_path(@response.project.id) if @response.project.present?
        end
      end
    else
      respond_to do |format|
        format.html { render :action => :new }
      end
    end
  end

  def edit
  end

  def update
    @response.safe_attributes = params[:response]
    complete_response_attributes

    if @response.save
      respond_to do |format|
        format.html do
          flash[:notice] = l(:notice_response_successfully_updated)
          # redirect_to responses_path
          redirect_to responses_path if @response.project.blank?
          redirect_to project_responses_path(@response.project.id) if @response.project.present?
        end
      end
    else
      respond_to do |format|
        format.html { render action: :edit }
      end
    end
  end

  def destroy
    @response.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = l(:notice_response_successfully_deleted)
        redirect_to(:back)
      end
    end
  end

  def add
    return if params[:response_id].blank?

    issue = Issue.find(params[:issue_id])
    response = Response.find(params[:response_id])
    response.note = params[:response_new_note]
    if issue.available_responses(User.current).include?(response)
      saved = issue.add_response(response, User.current)
    end
    if saved
      redirect_to issue, :notice => l(:notice_response_successfully_added)
    else
      redirect_to issue, :alert => l(:notice_response_not_added)
    end
  end

  def apply
    @issue = Issue.find(params[:issue_id])
    @response = Response.find(params[:response_id])
    return render_403 unless @issue.available_responses(User.current).include?(@response)
  end

  def update_note
    @issue = Issue.find(params[:issue_id])
    @response = Response.find(params[:response_id])
    return render_403 unless @issue.available_responses(User.current).include?(@response)

    respond_to do |format|
      format.js
    end
  end

  private

  def complete_response_attributes
    if User.current.allowed_to?(:manage_public_responses, @response.project) || User.current.admin?
      @response.visibility = (params[:response] && params[:response][:visibility]) || Response::VISIBILITY_PRIVATE
      @response.role_ids = params[:response] && params[:response][:role_ids]
    else
      @response.visibility = Response::VISIBILITY_PRIVATE
    end
  end

  def require_admin_or_author
    unless User.current.admin? || @response.author == User.current || User.current.allowed_to?(:edit_public_responses, @response.project)
      render_403
      return false
    end
    true
  end

  def require_delete_permission
    unless User.current.admin? || @response.author == User.current || User.current.allowed_to?(:delete_public_responses, @response.project)
      render_403
      return false
    end
    true
  end

  def find_response
    return unless require_login

    @response = Response.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def require_global
    if @response.project.present?
      global = Response.global_for_project(User.current, @response.project.id).include?(@response)
    else
      global = Response.owned_without_project(User.current).include?(@response)
    end

    render_403 unless global
  end
end

app/helpers/responses_helper.rb
# frozen_string_literal: true

module ResponsesHelper
  def options_for_responses_select(issue)
    responses = issue.available_responses
    tags = "".html_safe
    blank_text = "-- #{l(:label_responses)} --"
    tags << content_tag('option', blank_text, :value => '') unless responses.empty?
    tags << options_for_select(responses.map { |r| [r.name, r.id] })
    tags
  end

  # override principals_options_for_select ,to assign the response (with assigne to me) to the current user
  def principals_options_for_select_with_assigne_me_id_0(collection, selected=nil)
    s = +''
    if collection.include?(User.current)
      s << content_tag('option', "<< #{l(:label_me)} >>", :value => 0)
    end
    groups = +''
    collection.sort.each do |element|
      if option_value_selected?(element, selected) || element.id.to_s == selected
        selected_attribute = ' selected="selected"'
      end
      (element.is_a?(Group) ? groups : s) <<
        %(<option value="#{element.id}"#{selected_attribute}>#{h element.name}</option>)
    end
    unless groups.empty?
      s << %(<optgroup label="#{h(l(:label_group_plural))}">#{groups}</optgroup>)
    end
    s.html_safe
  end
end

app/views/responses/_action_menu_dropdown.html.erb
<% bottom ||= false %>
<% if bottom && @issue.available_responses(User.current).present? %>
  <span>
    <%= form_tag({ action: 'add', controller: 'responses' },
                { id: 'add_response_form' }) do %>
      <%= hidden_field_tag "issue_id", @issue.id %>
      <div class="flex-wrapper">
        <%= select_tag :response_id, options_for_responses_select(@issue) %>
        <%= submit_tag l(:button_send), id: 'add-response-submit', name: :send_response, disabled: true , :onclick => "$('#add-response-submit').attr('disabled', true);editResponseNote();" %>
        <input type="hidden" id="response_new_note" name="response_new_note" value="">
      </div>
    <% end %>
  </span>
<% end %>
<script>
  function editResponseNote() {
    let new_note = '';
    $.post('<%= update_note_responses_path %>', { response_id: $('#response_id :selected').val(), issue_id: $('#issue_id').val() })
      .done(function(data) {
        $('#add-response-submit').attr("disabled", false);       
      });
  }

  $(function () {
    // Here, we can't add class css, because of in prefabricated_responses.css there is style applied to the id
    let array_css = { "background-color": "#007bff", "border-color": "#621313", "color" : "#fff" };
    // if only one choice is available, it should be pre-selected
    if ($('#response_id option').length == 2){
      $('#response_id option:eq(1)').prop('selected', true);
      $('#response_id').trigger('change');
    }
    $('#response_id').change(function (e) {
        e.preventDefault()
      if ($('#response_id :selected').val()) {
        $('#add-response-submit').attr("disabled", false);
        $("#add-response-submit").css(array_css);
      } else {
        $("#add-response-submit").removeAttr('style');
        $('#add-response-submit').attr("disabled", true);
        }
      });
  });
</script>

app/views/responses/_edit_issue_dropdown.html.erb
<% if @issue.available_responses(User.current).present? %>
  <div style="margin-bottom: 8px;">
    <%= select_tag :response_id, options_for_responses_select(@issue), id: 'select-response-tag' %>
    <%= link_to l(:button_apply_to_form), '#', id: 'apply-response-submit', name: :apply_response , class: 'icon-prefabricated-responses link-disable' %>
  </div>
<% end %>

<script>
    $(function () {
        $('#apply-response-submit').click(function (e) {
            e.preventDefault()
            if ($('#select-response-tag :selected').val()) {
                $.ajax({
                    url: '<%= apply_responses_path %>',
                    type: 'post',
                    data: {
                        issue_id: <%= @issue.id %>,
                        response_id: $('#select-response-tag :selected').val()
                    }
                })
            }
        });
    });
    $(document).ready(function() {
        $('#apply-response-submit').removeAttr('href');
        $('#select-response-tag').change(function (e) {
            e.preventDefault()
            if ($('#select-response-tag :selected').val()) {
                $('#apply-response-submit').prop('href', '#');
                $("#apply-response-submit").removeClass('link-disable');
            } else {
                $('#apply-response-submit').removeAttr('href');
                $("#apply-response-submit").addClass('link-disable');
            }
        });
    });
</script>

app/views/responses/_form.html.erb
<%= labelled_form_for @response, :html => { :id => 'response_form' } do |f| %>

  <%= error_messages_for @response %>

  <div class="box tabular">
    <div id="response_attributes">

      <p><%= f.text_field :name, { label: l(:field_name), required: false, size: 80 } %></p>
      <p>
        <%= f.check_box :enabled, { label: l(:label_enabled) } %>
      </p>
      <%= hidden_field_tag 'response[project_id]', @response.project.present? ? @response.project.id : '' %>
      <% if User.current.admin? ||
        User.current.allowed_to?(:manage_public_responses, @response.project) %>
        <p>
          <label><%= l(:field_visible) %></label>
          <label class="block"><%= f.radio_button :visibility, Response::VISIBILITY_PRIVATE %>
            <%= l(:label_visibility_private) %>
          </label>
          <label class="block"><%= f.radio_button :visibility, Response::VISIBILITY_PUBLIC %>
            <%= l(:label_visibility_public) %>
          </label>
          <% if @response.project.present? %>
            <label class="block">
              <%= f.radio_button :visibility, Response::VISIBILITY_ROLES %>
              <%= l(:label_visibility_roles) %>:
            </label>
            <% Role.givable.sorted.each do |role| %>
              <label class="block role-visibility"><%= check_box_tag 'response[role_ids][]', role.id, @response.roles.include?(role), :id => nil %> <%= role.name %></label>
            <% end %>
            <%= hidden_field_tag 'response[role_ids][]', '' %>
          <% end %>
        </p>
      <% end %>

      <% if @response.project.present? %>
        <p>
          <%= f.text_field :project, disabled: true %>
        </p>
      <% end %>
      <p>
        <%= f.select :initial_status_ids,
                     options_for_select(IssueStatus.sorted.map { |s| [s.name, s.id] }, @response.initial_status_ids),
                     { label: l(:field_initial_status_plural) },
                     { class: "orga-select2", multiple: true, :onchange => "update_checkbox(this, 'select_all_status', #{IssueStatus.count})" } %>
        <span>
          <%= check_box_tag :select_all_status, :select_all_status, (@response.initial_status_ids.present? && @response.initial_status_ids.count == IssueStatus.count), :onclick => "selectAll(this, 'response_initial_status_ids')" %>
          <%= label_tag :select_all_status, l(:label_select_all), { class: "checkbox inline" } %>
        </span>
      </p>

      <p>
        <%= f.select :final_status_id,
                     options_for_select(IssueStatus.sorted.map { |s| [s.name, s.id] }, @response.final_status_id),
                     { label: l(:field_final_status), required: false, include_blank: true },
                     { class: "orga-select2", multiple: false } %>
        <span><i><%= l('hint_no_final_status') %></i></span>
      </p>

      <p>
        <%= f.text_field :author, disabled: true %>
      </p>

      <!--
      <p>
        <%= f.label l(:label_project_plural) %>
        <span class="select_projects" id="select_projects" style="display: block;">
              <%# f.select :project_ids, project_tree_options_for_select(@response.allowed_target_projects, :selected => @response.projects),
                          { :required => false, label: "" },
                          { :multiple => true, :size => 10, style: "display:none;" } %>
          <span id="my_projects">
              <%# @response.projects.each do |project| %>
                <%# content_tag("span", project.name.gsub(/ /, "&nbsp;").html_safe, class: "list_projects_names") %>
              <%# end %>
            </span>
          </span>

        <%# link_to l("button_edit"), '#', id: "link_update_project_list", :onclick => 'showModal("ajax-modal", "1000px");$("#button_apply_projects").focus();' %>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#ajax-modal').html('<%# escape_javascript(render :partial => 'responses/modal_select_projects') %>');
            });
        </script>
      </p>
      -->
      <p>
        <% @users = @response.project.present? ? @response.project.assignable_users : User.active.sorted %>
        <%= f.select :assigned_to_id,
                     principals_options_for_select_with_assigne_me_id_0(@users, @response.assigned_to), :include_blank => true %>
      </p>
      <p><%= f.select :tracker_ids,
                      options_for_select(Tracker.sorted.map { |s| [s.name, s.id] }, @response.tracker_ids),
                      { label: l(:label_tracker_plural) },
                      { class: "orga-select2", multiple: true, :onchange => "update_checkbox(this, 'select_all_tracker', #{Tracker.count})" } %>
        <span>
          <%= check_box_tag :select_all_tracker, :select_all_tracker, (@response.tracker_ids.present? && @response.tracker_ids.count == Tracker.count), :onclick => "selectAll(this, 'response_tracker_ids')" %>
          <%= label_tag :select_all_tracker, l(:label_select_all), { class: "checkbox inline" } %>
        </span>
      </p>

      <p>
        <%= f.text_area :note, rows: 6, label: l(:label_auto_update_note) %>
        <%= wikitoolbar_for 'response_note' %>
      </p>


      <% if false
           #Redmine::Plugin.installed?(:redmine_organizations) %>
        <p>
          <%= f.select :organization_ids,
                       options_for_select(nested_set_options(Organization) { |i| i.fullname }, @response.organization_ids),
                       { label: l(:field_issues_assigned_to) },
                       { class: "orga-select2", multiple: true } %>
        </p>
      <% end %>

    </div>
  </div>

  <p>
    <%= submit_tag l(:button_save) %>
    <% if @response.project.present? %>
      <%= link_to l(:button_cancel), project_responses_path(@response.project.id) %>
    <% else %>
      <%= link_to l(:button_cancel), responses_path %>
    <% end %>
  </p>

<% end %>
<script>
    $(document).ready(function () {
        $("input[name='response[visibility]']").change(function () {
            var roles_checked = $('#response_visibility_1').is(':checked');
            var private_checked = $('#response_visibility_0').is(':checked');
            $("input[name='response[role_ids][]'][type=checkbox]").attr('disabled', !roles_checked);
        }).trigger('change');
    });
</script>

app/views/responses/_modal_select_projects.html.erb
<% nested_projects_list = render_project_nested_lists(@response.allowed_target_projects) do |project|
  content_tag('label',
              check_box_tag(
                'project_ids[]',
                project.id,
                @response.present? && @response.projects.include?(project)
              ) + ' ' + h(project.name))
end
%>

<h3 class="title"><%= l(:label_project_plural) %></h3>

<div class="actions_links">
  <%= l("Selection") %> :
  <%= link_to l("select_all"), '#', id: "link_select_all", :onclick => "select_all()" %>
  |
  <%= link_to l("select_none"), '#', id: "link_select_all", :onclick => "select_none()" %>
</div>

<div class="projects_container">
  <div class="columns" id="project_nested_list">
    <%= nested_projects_list %>
  </div>
</div>

<p class="buttons">
  <%= submit_tag l(:button_apply), :name => nil, :onclick => "updateSelectedProjects();hideModal(this);", :type => 'button', :id => 'button_apply_projects' %>
</p>

<script type="text/javascript">

    function updateSelectedProjects() {
        $("select#response_project_ids option").each(function () {
            this.selected = "";
        });
        var htmlContent = "";
        $("input:checkbox[name='project_ids[]']:checked").each(function () {
            $("#response_project_ids option[value=" + $(this).val() + "]").prop("selected", true);
        });

        $("input:checkbox[name='project_ids[]']:checked:not(.inactive)").each(function () {
            htmlContent += "<span class=\"list_projects_names\">" + $(this).closest('label').text() + "</span>";
        });
        $("#my_projects").html(htmlContent);
    }

    function select_all() {
        $("input:checkbox[name='project_ids[]']").each(function () {
            this.setAttribute("checked", "checked");
            this.checked = true;
        });
    }

    function select_none() {
        $("input:checkbox[name='project_ids[]']:checked:not(.inactive)").each(function () {
            $(this).attr("checked", "");
            $(this).removeAttr("checked");
            $(this).checked = false;
        });
    }

    $('#project_nested_list').on('change', "input:checkbox[name='project_ids[]']", function (event) {
        $(event.target).closest('li').find("input:checkbox[name='project_ids[]']").prop('checked', $(event.target).is(':checked'));
    })

</script>

app/views/responses/_update_modal.erb
<h3 class="title"><%=l(:label_edit_note_before_sending)%></h3>
<div class="box tabular">
  <p>
    <%= label_tag l(:label_auto_update_note) %>
    <%= text_area_tag :response_note, @response.note, rows: 6  %>
  </p>
  <%= hidden_field_tag "issue_id", @issue.id %>
  <%= hidden_field_tag "response_id", @response.id %>
</div>
<p class="buttons">
  <%= link_to_function l(:button_cancel), "hideModal(this);" %>
  <%= submit_tag l(:button_send), :name => nil, onclick: "update_note();" %>
</p>

<script>
  function update_note() {
    $('#response_new_note').val($('#response_note').val());
    hideModal(this);
    $('#add_response_form').submit();
  }
</script>

app/views/responses/apply.js.erb
$('#issue_notes').val(`<%= @response.note.html_safe %>`)
//if the option (Setting.plugin_redmine_wysiwyg_editor[:visual_editor_mode_switch_tab]) is enabled
if (($('.wysiwyg-editor-tab').length)) {
  $('.wysiwyg-editor-tab a[data-type="text"]').click();
} else {
  $(".tab-rwe-text").click();
}

<% if @response.final_status_id.present? %>
$('#issue_status_id').val(`<%= @response.final_status_id %>`)
<% end %>
<% if @response.assigned_to_id.present? %>
  <% if @response.assigned_to_id == 0 %>
$('#issue_assigned_to_id').val(`<%= User.current.id %>`)
  <% else %>
$('#issue_assigned_to_id').val(`<%= @response.assigned_to_id %>`)
  <% end %>
<% end %>

app/views/responses/edit.html.erb
<div class=contextual>
  <% if @response.project.present? %>
    <%= link_to l(:label_all_responses_for_project), project_responses_path(@response.project.id), class: "icon-prefabricated-responses" %>
  <% else %>
    <%= link_to l(:label_all_responses), responses_path, class: "icon-prefabricated-responses" %>
  <% end %>
</div>

<h2><%= "#{l(:label_edit_response)}" %></h2>

<div id="all_attributes">
  <%= render :partial => 'form' %>
</div>

<script>
    $(function () {
        let assigne_to_id = "<%= @response.assigned_to_id%>";
        if (assigne_to_id == "0") {
            $("select[name='response[assigned_to_id]'] option:eq(1)").attr('selected', 'selected');
        }
    });
</script>

app/views/responses/index.html.erb
<% html_title(l(:label_responses)) %>

<div class="contextual">
  <% if @project %>
    <%= link_to l(:label_new_response_for_project), new_project_response_path(@project), :class => 'icon icon-add' %>
  <% else %>
    <%= link_to l(:label_new_response), new_response_path, :class => 'icon icon-add' %>
  <% end %>
</div>

<h2><span class="icon icon-prefabricated-responses"><%= h "#{l(:label_responses)}" %></span></h2>

<% if @notice %>
  <div class="flash notice"><%= @notice %></div>
<% end %>

<% if @responses.empty? %>
  <div class="responses_box">
    <%= l(:no_responses) %>
  </div>
<% else %>

  <div class="responses_box">

    <table class="list responses" id="responses_list">
      <thead>
      <tr>
        <th><%= l(:label_enabled) %></th>
        <th><%= l(:field_name) %></th>
        <th class="response_initial_status"><%= l(:field_initial_status_plural) %></th>
        <th class="response_final_status"><%= l(:field_final_status) %></th>
        <!-- <th><%= l(:label_project_plural) %></th> -->
        <th><%= l(:label_tracker_plural) %></th>
        <th><%= l(:label_author) %></th>
        <!-- <th><%= l(:field_time_limit) %></th> -->
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @responses.each do |response| %>
        <% initial_statuses = (response.initial_status_ids.length == IssueStatus.all.length) ? l(:label_all_status) : IssueStatus.where(id: response.initial_status_ids).join(', ') %>
        <% final_status = IssueStatus.where(id: response.final_status_id).join(', ') %>
        <% trackers = Tracker.where(id: response.tracker_ids).join(', ') %>
        <tr class="response">
          <td><span class="<%= response.enabled ? 'icon icon-ok' : 'icon icon-not-ok' %>"></span></td>
          <td><%= link_to response.name, response_path(response) %></td>
          <td><%= h(initial_statuses) %></td>
          <td><%= h(final_status) %></td>
          <!-- <td><%# (response.projects.size < 3 ? response.projects.map(&:name).join(', ') : "#{response.projects.count} #{l(:label_project_plural)}") if response.projects.any? %></td> -->
          <td><%= h(trackers) %></td>
          <td><%= link_to_user response.author %></td>
          <!-- <td><%= l 'time_in_days', days: response.time_limit %></td> -->

          <td class="buttons">
            <%= link_to l(:button_show), response_path(response), :class => 'icon icon-list' %>
            <% if User.current.admin? || response.author == User.current || User.current.allowed_to?(:edit_public_responses, response.project) %>
              <%= link_to l(:button_edit), edit_response_path(response), :class => 'icon icon-edit' %>
            <% end %>
            <% if User.current.admin? || response.author == User.current || User.current.allowed_to?(:delete_public_responses, response.project) %>  
              <%= delete_link response_path(response) %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

<% end %>

app/views/responses/new.html.erb
<div class=contextual>
  <% if @response.project.present? %>
    <%= link_to l(:label_all_responses_for_project), project_responses_path(@response.project.id), class: "icon-prefabricated-responses" %>
  <% else %>
    <%= link_to l(:label_all_responses), responses_path, class: "icon-prefabricated-responses" %>
  <% end %>
</div>
<% if @response.project.present? %>
  <h2><%=l(:label_new_response_for_project)%></h2>
<% else %>
  <h2><%=l(:label_new_response)%></h2>
<% end %>
<div id="all_attributes">
  <%= render :partial => 'responses/form' %>
</div>

app/views/responses/update_note.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'responses/update_modal') %>');
showModal('ajax-modal', '600px');